---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want know host name
    command:  hostname -f
    register: myresult
  - name: i want to display the result
    debug:
      msg: "{{myresult}}"