---
- hosts: mywebservers
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to install webserver
    apt:
     name: apache2
     state: present
     notify: restartwebserver



  
  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted