---
-  hosts: all
   become: yes
   tasks: 
   - name: i want to ping all nodes
     ping:
     
   - name: i want to install git
     apt:
      name: git
      
   - name: i want to install tree
     apt:
       name: tree
       state: present
   - name: i want install webserver
     apt:
      name: apache2
      state: absent
   