---
- hosts: myapplications
  become: yes
  tasks:
  - name: uninstall git,tree,wget
    apt:
      name: "{{item}}"
      state: absent
    loops:
       - git
       - tree
       - wget
       
    
  