---
- hosts: myapplications
  become: yes
  tasks:
  - name: uninstall git,tree,wget
    apt:
      name: "{{ item }}"
      state: present
    loops:
       - git
       - tree
       - wget
       
    
  