---
- hosts: mywebservers
  become: yes
  vars:
    mykey1: devops
    mykey2: aws
    mykey3: linux
  tasks:
  - name: display  mykey1
    debug:
      msg: "{{mykey1}}"
  - name: display mykey2
    debug:
      msg: "{{mykey2}}"