---
- name: download  remote file of java application from s3
   get_url:
    url: https://mahadevops.s3-us-west-2.amazonaws.com/mahaLogin.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    force_basic_auth: yes