---


- name: create tomcat folder
  file:
    path: /opt/tomcat
    state: directory
    mode: '0755'

- name: tom tar file extract
  unarchive:
    src: /home/ubuntu/apache-tomcat-8.5.5.tar.gz
    dest: /opt/tomcat
    extra_opts: [--strip-components=1]
    remote_src: yes