---


- name: create tomcat folder
  file:
    path: /opt/tomcat
    state: directory
    mode: '0755'

- name: tom tar file extract
  command:
    cmd:  tar xzvf /home/ubuntu/apache-tomcat-8.5.5.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE