---
- name: create group
  group:
    name: tomcat
    state: present

- name: create tom user
  user:
    name: tomcat
    shell: /bin/false
    home: /opt/tomcat
    comment: this my tom user
    group: tomcat